### ISSUE TITLE
[Question] Does Negroni support multiple handlers in the same URL?

### ISSUE THREAD

**Issue by vegax87** [codegangsta/negroni#70]
I'm trying to convert this code: https://github.com/GopherCasts/Lessons/blob/master/lesson9/main.go
from Martini to Negroni, and I would like to know if Negroni or an external router supports 2 handlers (for example: RequireLogin and SecretPath) like this snippet:

func main() {
// ....
	m.Get("/", RequireLogin, SecretPath)
	m.Post("/login", PostLogin)
	m.Get("/logout", Logout)
	m.Post("/signup", Signup)

	m.Run()
}

**Comment by pjebs** [comment]
Yes, you need to create another Negroni instance and have that instance handle m.Get("/", X).

That previously mentioned new New Negroni instance (labelled X above) needs have SecretPath as its end handler and RequireLogin as 'middleware' which always calls "next".

See example code and modify since its not precisely what you want: https://github.com/pjebs/restgate

Alternatively, create a brand new handler which happens to call both RequireLogin and SecretPath inside.

**Comment by pjebs** [comment]
My suspicion is that you actually don't want RequireLogin and SecretPath to run. You want SecretPath to run ONLY if REquireLogin detects that user is logged in.

In which case, that is PRECISELY what middleware is for. RequireLogin should be middleware that only calls "next" if user is actually logged in. (in order to proceed to next middleware in middleware stack OR end-handler (i.e. SecretPath) if no other middleware is present in stack)

**Comment by vegax87** [comment]
how does "next" works in this case?

**Comment by pjebs** [comment]
https://github.com/codegangsta/negroni#handlers

http://mattstauffer.co/blog/laravel-5.0-middleware-filter-style

**Comment by codegangsta** [comment]
hope this answered your question. Closing this out
