### ISSUE TITLE
How to use with julienschmidt/httprouter?

### ISSUE THREAD

**Issue by leadinglocally** [codegangsta/negroni#86]
Is it possible to use this package with:

https://github.com/julienschmidt/httprouter#where-can-i-find-middleware-x

...for an Auth0 implementation?

**Comment by yanfali** [comment]
It's pretty easy to use httprouter with negroni. See http://nicolasmerouze.com/guide-routers-golang/

You're biggest issue is probably going to be dealing with the different handler signature. One strategy is to use gorilla context lib and stuff the Param object in there so that your signature stays closer to http.HandlerFunc. The fine article has the details.

**Comment by meatballhat** [comment]
@leadinglocally I'm closing this out in the hope that you've found a suitable solution.  Please yell if you'd like the issue reopened!  😺

**Comment by laurentbel** [comment]
Check this out: https://github.com/laurentbel/go-auth0-jwt-validation-middleware-httprouter
Hope this will eventually help someone.
